version: '3.9'
services:
  frontend:
    container_name: kupipodariday-front
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - frontend
    image: kupipodariday-front-image
    ports:
      - 8081:80

  backend:
    container_name: kupipodariday-back
    build:
      context: backend
      dockerfile: Dockerfile
    networks:
      - backend
    image: kupipodariday-back-image
    ports:
      - 4000:3000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    networks:
      - backend
    image: postgres
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - .env

  adminer:
    container_name: adminer
    networks:
      - backend
    image: adminer
    ports:
      - 8085:8080
    depends_on:
      - postgres

networks:
  frontend:
  backend:

volumes:
  postgres_data:
